require("winghaa")
-- vim.cmd("colorscheme tokyonight-night")
vim.cmd("colorscheme onedark")
-- vim.cmd("colorscheme catppuccin-macchiato")
-- vim.cmd("colorscheme kanagawa")
-- vim.cmd("colorscheme everforest")
-- vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme rose-pine")
