return {
    filetypes = {
        "astro",
        "blade",
        "css",
        "eruby",
        "gotmpl",
        "html",
        "htmlangular",
        "htmldjango",
        "javascriptreact",
        "less",
        "pug",
        "sass",
        "scss",
        "svelte",
        "typescriptreact",
        "vue",
    },
}
